# Site settings
title: Quoc Tin Phan's personal page
description: This is personal website of Quoc Tin Phan
url: "http://quoctin.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author:
  name     : Quoc Tin Phan
  bio      : My research interest is multimedia forensics, especially forensic investigations in blind scenarios. I am also passionate in studying sparse coding and machine learning.
  email    : quoctin.phan@unitn.it
  twitter  :

# Build settings
permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/projects/page/:num"

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

css_folder:  "/assets/css"
js_folder:  "/assets/js"
img_folder:  "/assets/img"
sass:
    style: compressed
