# Site settings
title: Quoc Tin Phan's personal page
description: This is personal website of Quoc Tin Phan
url: "http://quoctin.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author:
  name     : Quoc Tin Phan
  bio      : I am Quoc Tin Phan, the 3rd-year PhD student of the University of Trento, Italy. My research interest is multimedia forensics and applied machine learning.
  email    : quoctin.phan@unitn.it
  twitter  :

# Build settings
permalink: /:title/
markdown: kramdown
# paginate: 5
# paginate_path: "/projects/page/:num"
paginate_multiple:
  - paginate: 5
    paginate_path: "/blogs/page:num/"
    sub_dir: "/blogs"
  - paginate: 5
    paginate_path: "/projects/page:num/"
    sub_dir: "/projects"

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

css_folder:  "/assets/css"
js_folder:  "/assets/js"
img_folder:  "/assets/img"
sass:
    style: compressed
